In [156]:
import matplotlib.pyplot as plt 
%matplotlib inline
import pandas as pd
import numpy as np
from skimage import io
from IPython import display
from bokeh.io import output_notebook, show
from bokeh.plotting import figure
output_notebook()

import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
sns.set(color_codes=True)

Loading BokehJS ...

__Problem:__ a partir de data de banques variées sur des prets acceptés ou non à des entreprises, prédire si un pret va etre accepté par la banque ou non ?
20 attributs differents, 1 variable objectif(class/label): Accept (0=NO, 1=YES)

In [157]:
df = pd.read_csv('loan-approval-prediction-new-york/train.csv')
df.head()

/var/folders/jj/m28xy22x5w74b624rj27hpn80000gn/T/ipykernel_11378/2251491112.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('loan-approval-prediction-new-york/train.csv')


id  LoanNr_ChkDgt                            Name  \
0  b353a0b461c     3354343008        TOGETHER GARGOYLES, INC.   
1  cca24bbcc48     2349745003  LAWRENCE K. ALTHISER DBA LARRY   
2  e60644381ce     6007284009        TAAMEER CONSTRUCTION INC   
3  ffca41a2760     6047703002   CENTRAL CONTROL SYSTEMS, INC.   
4  79e48255003     6590164004                     METRO SALON   

                             City State                            Bank  \
0                        BROOKLYN    NY  JPMORGAN CHASE BANK NATL ASSOC   
1                        HARTWICK    NY        CITIZENS BANK NATL ASSOC   
2  BROOKLYN (BOROUGH OF NEW YORK)    NY  JPMORGAN CHASE BANK NATL ASSOC   
3                        SYRACUSE    NY   MANUFACTURERS & TRADERS TR CO   
4                       ROCHESTER    NY   MANUFACTURERS & TRADERS TR CO   

  BankState ApprovalDate ApprovalFY  NoEmp  ...  CreateJob  RetainedJob  \
0        NY    21-Dec-88       1989     20  ...          0            0   
1        RI    23-Mar-07       2007      3  ...          1            4   
2        IL     9-Jan-03       2003      5  ...          0            5   
3        NY    10-Nov-93       1994     25  ...          0            0   
4        NY    14-Aug-03       2003      6  ...          0            0   

   FranchiseCode  UrbanRural  RevLineCr LowDoc DisbursementDate  \
0              0           0          N      N        30-Apr-89   
1              0           2          N      N        30-Apr-07   
2              1           1          0      N        31-Jan-03   
3              1           0          N      N        31-Jan-94   
4              1           1          0      Y        30-Sep-03   

  DisbursementGross BalanceGross Accept  
0      $350,000.00        $0.00       1  
1       $35,000.00        $0.00       1  
2       $50,000.00        $0.00       1  
3      $190,000.00        $0.00       1  
4       $30,000.00        $0.00       1  

[5 rows x 21 columns]

In [158]:
def gross_extract(word):  #to remove the '$'sign 
    return word.split('$')[1].split(',')[0]

df['Disb Gross'] = df['DisbursementGross'].apply(gross_extract)
df['Balance Gross'] = df['BalanceGross'].apply(gross_extract)
df.head()

id  LoanNr_ChkDgt                            Name  \
0  b353a0b461c     3354343008        TOGETHER GARGOYLES, INC.   
1  cca24bbcc48     2349745003  LAWRENCE K. ALTHISER DBA LARRY   
2  e60644381ce     6007284009        TAAMEER CONSTRUCTION INC   
3  ffca41a2760     6047703002   CENTRAL CONTROL SYSTEMS, INC.   
4  79e48255003     6590164004                     METRO SALON   

                             City State                            Bank  \
0                        BROOKLYN    NY  JPMORGAN CHASE BANK NATL ASSOC   
1                        HARTWICK    NY        CITIZENS BANK NATL ASSOC   
2  BROOKLYN (BOROUGH OF NEW YORK)    NY  JPMORGAN CHASE BANK NATL ASSOC   
3                        SYRACUSE    NY   MANUFACTURERS & TRADERS TR CO   
4                       ROCHESTER    NY   MANUFACTURERS & TRADERS TR CO   

  BankState ApprovalDate ApprovalFY  NoEmp  ...  FranchiseCode  UrbanRural  \
0        NY    21-Dec-88       1989     20  ...              0           0   
1        RI    23-Mar-07       2007      3  ...              0           2   
2        IL     9-Jan-03       2003      5  ...              1           1   
3        NY    10-Nov-93       1994     25  ...              1           0   
4        NY    14-Aug-03       2003      6  ...              1           1   

   RevLineCr  LowDoc  DisbursementDate DisbursementGross BalanceGross Accept  \
0          N       N         30-Apr-89      $350,000.00        $0.00       1   
1          N       N         30-Apr-07       $35,000.00        $0.00       1   
2          0       N         31-Jan-03       $50,000.00        $0.00       1   
3          N       N         31-Jan-94      $190,000.00        $0.00       1   
4          0       Y         30-Sep-03       $30,000.00        $0.00       1   

  Disb Gross Balance Gross  
0        350         0.00   
1         35         0.00   
2         50         0.00   
3        190         0.00   
4         30         0.00   

[5 rows x 23 columns]

In [159]:
print(df.columns, 'shape : ' , df.shape)#les 21 attributs

Index(['id', 'LoanNr_ChkDgt', 'Name', 'City', 'State', 'Bank', 'BankState',
       'ApprovalDate', 'ApprovalFY', 'NoEmp', 'NewExist', 'CreateJob',
       'RetainedJob', 'FranchiseCode', 'UrbanRural', 'RevLineCr', 'LowDoc',
       'DisbursementDate', 'DisbursementGross', 'BalanceGross', 'Accept',
       'Disb Gross', 'Balance Gross'],
      dtype='object') shape :  (40385, 23)


In [160]:
#df.describe()

# Graph visualization
Too see 'Accept' proportion in function of each parameter 

In [161]:
#df.hist(figsize=(10,10))
#plt.show()

In [162]:
#df.hist(column='LowDoc', by='Accept', sharey=True)

In [163]:
#df.hist(column='RevLineCr', by='Accept', sharey=True)

In [164]:
#df.hist(column='UrbanRural', by='Accept', sharey=True)

In [165]:
#sns.barplot(x='LowDoc', y='Accept', data=df) # LowDoc Loan Program: Y = Yes, N = No

In [166]:
#sns.barplot(x='NewExist', y='Accept', data=df)

In [167]:
#sns.barplot(x='RevLineCr', y='Accept', data=df) # Revolving line of credit: Y = Yes, N = No

In [168]:
#sns.barplot(x='UrbanRural', y='Accept', data=df) # 1 = Urban, 2 = rural, 0 = undefined

In [169]:
#sns.barplot(x='BankState', y='Accept', data=df)

In [170]:
#df.groupby('CreateJob').Accept.mean().plot()

In [171]:
#df.groupby('RetainedJob').Accept.mean().plot()

# Parameter analysis and Processing 
To know the possible values for the parameters and their numbers. Remove nan and assign most common value. Convert some character into 0 and 1 : 

In [172]:
print(df['City'].unique()) #bcp de villes (2552), non utilisable ?
df['City'].unique().shape

['BROOKLYN' 'HARTWICK' 'BROOKLYN (BOROUGH OF NEW YORK)' ... 'OCEQNSIDE'
 'LITTLE YORK' 'ELLERY']


(2552,)

In [173]:
df['State'].unique().shape #todos son de NY, unrelevant feature

(1,)

In [174]:
df['LowDoc'].unique() # pas que des yes ou no , que veut dire R ? C ? 

array(['N', 'Y', nan, '0', 'R', 'C', 'S', 'A'], dtype=object)

In [175]:
df['RevLineCr'].unique()

array(['N', '0', 'Y', 'T', nan], dtype=object)

__Value binarization for param LowDoc__

In [176]:
df.loc[df["LowDoc"] == "N", "LowDoc"] = 0
df.loc[df["LowDoc"] == "Y", "LowDoc"] = 1
df.loc[df["LowDoc"] == "0", "LowDoc"] = 0
df.loc[df["LowDoc"] == "R", "LowDoc"] = 1
df.loc[df["LowDoc"] == "C", "LowDoc"] = 1
df.loc[df["LowDoc"] == "S", "LowDoc"] = 1
df.loc[df["LowDoc"] == "A", "LowDoc"] = 1
df['LowDoc'].fillna(1, inplace=True) 
#what to do with  R C S A & nan ? assign 0 to all of them ? or 1 ? create a third class ?

In [177]:
df['LowDoc'].unique()

array([0, 1])

__Value binarization for param RevLineCr__

In [182]:
df.loc[df["RevLineCr"] == "N", "RevLineCr"] = 0
df.loc[df["RevLineCr"] == "Y", "RevLineCr"] = 1
df.loc[df["RevLineCr"] == "0", "RevLineCr"] = 1
df.loc[df["RevLineCr"] == "T", "RevLineCr"] = 1
df['RevLineCr'].fillna(1, inplace=True) 

In [183]:
df['RevLineCr'].unique()

array([0, 1])

In [207]:
df.loc[df["ApprovalFY"] == "1976A", "ApprovalFY"] = 1976

__Numerization of param 'Bank' and 'Bankstate'__

In [215]:
for i in range(0, 312): #we assign an int to identify each bank
    df.loc[df["Bank"] == index[i] , "Bank"] = i 
#df.head()
df['Bank'].fillna(312, inplace=True)
#df['Bank'].unique()

In [217]:
df['BankState'].fillna('NY', inplace=True)
index_S = df["BankState"].unique() #we assign an int to identify each bank state
for i in range (0, 37):
    
    df.loc[df["BankState"] == index_S[i] , "BankState"] = i
#df.head()
#df['BankState'].unique()

In [203]:
df['NewExist'].fillna(2, inplace=True)  #replaced NaN by 2 but maybe 0 or 1 can be better ?
df['NewExist'].unique()

array([1., 2., 0.])

In [188]:
df['Balance Gross'].unique() #irrelevant feature ? , always 0 in the training

array(['0.00 '], dtype=object)

# Different algorithm and their accuracy with some parameters 

In [208]:
from sklearn.model_selection import train_test_split
features = ['BankState', 'Bank', 'NoEmp', 'NewExist','CreateJob', 'RetainedJob', 'Disb Gross', 'ApprovalFY']
X = df[features].values
y = df['Accept'].values 
from sklearn import preprocessing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=33, stratify=y) #75% training 25%test
scaler = preprocessing.StandardScaler().fit(X_train) #preprocess : standardize/normalize
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [209]:
from sklearn.tree import DecisionTreeClassifier
decision_tree = DecisionTreeClassifier()
decision_tree.fit(X_train, y_train)
Y_pred_dec_tree = decision_tree.predict(X_test)
from sklearn.metrics import plot_confusion_matrix
from sklearn import metrics
print('Confusion matrix for decision tree : \n', metrics.confusion_matrix(y_test, Y_pred_dec_tree))
print("Exactitud del conjunto de entrenamiento: {:.3f}".format(decision_tree.score(X_train, y_train)))
print("Exactitud del conjunto de test: {:.3f}".format(decision_tree.score(X_test, y_test)))

Confusion matrix for decision tree : 
 [[ 1977  2135]
 [ 2515 13566]]
Exactitud del conjunto de entrenamiento: 0.986
Exactitud del conjunto de test: 0.770


In [210]:
from sklearn.linear_model import Perceptron
perceptron = Perceptron()
perceptron.fit(X_train, y_train)
Y_pred_perceptron = perceptron.predict(X_test)
from sklearn.metrics import plot_confusion_matrix 
print('Confusion matrix for perceptron model : \n', metrics.confusion_matrix(y_test, Y_pred_perceptron))
print("Exactitud del conjunto de entrenamiento: {:.3f}".format(perceptron.score(X_train, y_train)))
print("Exactitud del conjunto de test: {:.3f}".format(perceptron.score(X_test, y_test)))

Confusion matrix for perceptron model : 
 [[  314  3798]
 [ 3522 12559]]
Exactitud del conjunto de entrenamiento: 0.648
Exactitud del conjunto de test: 0.637


In [211]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train, y_train)
Y_pred_rdm_forest = random_forest.predict(X_test)
random_forest.score(X_train, y_train)
print('Confusion matrix for random forest classifier : \n', metrics.confusion_matrix(y_test, Y_pred_rdm_forest))
print("Exactitud del conjunto de entrenamiento: {:.3f}".format(random_forest.score(X_train, y_train)))
print("Exactitud del conjunto de test: {:.3f}".format(random_forest.score(X_test, y_test)))

Confusion matrix for random forest classifier : 
 [[ 1723  2389]
 [ 1113 14968]]
Exactitud del conjunto de entrenamiento: 0.986
Exactitud del conjunto de test: 0.827


In [212]:
from sklearn.naive_bayes import GaussianNB
clf_NB = GaussianNB()
clf_NB.fit(X_train, y_train)
y_pred_NB = clf_NB.predict(X_test)
print('Confusion matrix for random forest classifier : \n', metrics.confusion_matrix(y_test, y_pred_NB))
print("Exactitud del conjunto de entrenamiento: {:.3f}".format(clf_NB.score(X_train, y_train)))
print("Exactitud del conjunto de test: {:.3f}".format(clf_NB.score(X_test, y_test)))

Confusion matrix for random forest classifier : 
 [[  561  3551]
 [  515 15566]]
Exactitud del conjunto de entrenamiento: 0.799
Exactitud del conjunto de test: 0.799


In [213]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(max_iter=3000,activation = 'tanh',solver='adam',random_state=1, hidden_layer_sizes=(5,3)) 
mlp.fit(X_train, y_train)
print("Exactitud del conjunto de entrenamiento: {:.3f}".format(mlp.score(X_train, y_train)))
y_pred_mlp = mlp.predict(X_test)
print("Exactitud del conjunto de test: {:.3f}".format(mlp.score(X_test, y_test)))
print('Confusion matrix for random forest classifier : \n', metrics.confusion_matrix(y_test, y_pred_mlp))

Exactitud del conjunto de entrenamiento: 0.818
Exactitud del conjunto de test: 0.813
Confusion matrix for random forest classifier : 
 [[ 1097  3015]
 [  761 15320]]


In [214]:
from sklearn.ensemble import GradientBoostingClassifier
clf=GradientBoostingClassifier()
clf.fit(X_train, y_train)
print("Exactitud del conjunto de entrenamiento: {:.3f}".format(clf.score(X_train, y_train)))
y_pred_clf = clf.predict(X_test)
print("Exactitud del conjunto de test: {:.3f}".format(clf.score(X_test, y_test)))
print('Confusion matrix for random forest classifier : \n', metrics.confusion_matrix(y_test, y_pred_clf))

Exactitud del conjunto de entrenamiento: 0.844
Exactitud del conjunto de test: 0.842
Confusion matrix for random forest classifier : 
 [[ 1456  2656]
 [  536 15545]]
